### ISSUE TITLE
Looks like .env file is missing...

### ISSUE THREAD

**Issue by im-rahulr** [sinnedpenguin/dennx#2]
> I do not have a `.eve` file. As I mentioned before, there is no `.eve` file in the dennx repository.

It appears that you are mistaken. The command `find .eve` is searching for a file named `.eve` in the current directory and all of its subdirectories. Since there is no `.eve` file in the dennx repository, the command will not find anything.

If you are trying to update the API key, you can follow these steps:

1. Open the `.env` file in your text editor.
2. Find the line that starts with `API_KEY=` and replace the existing API key with your own API key.
3. Save the `.env` file.

Once you have updated the API key in the `.env` file, you can restart your Flask app and the new API key will be used.
Cloned site : [](https://dennxi.vercel.app/api/auth/error)

**Comment by sinnedpenguin** [comment]
Hi. .env is not included, of course.
